### ISSUE TITLE
NeoGrbFeature and Neo800KbpsMethod

### ISSUE THREAD

**Issue by promd** [Makuna/NeoPixelBus#111]
Hi, I can't make it work.....
Always getting an Error 
"Type 'NeoGrbFeature' could not be resolved" 
and 
"Type 'Neo800KbpsMethod' could not be resolved".

on line
`NeoPixelBus<NeoGrbFeature,Neo800KbpsMethod> strip(pixelCount, pixelPin);`

And yes, I can't see them defined anywhere.
It seems to be something is missing from the sources ?? 
I am on platform.io, for platform espressif (esp12).

**Comment by Makuna** [comment]
Your code or a sample?  Please include the sketch or a reference to the example.
I do not use nor test with platform io.  I tried to set it up once and got too many failures during installations.  This library was written for Arduino.

Is ARDUINO_ARCH_ESP8266 defined in your build?

**Comment by promd** [comment]
Nevermind. Seems they are using a rather old version of your Library. I did clone from Git, and I am running now - Thx!
