### ISSUE TITLE
NeoPixelBus::ClearTo on a single pixel does not work

### ISSUE THREAD

**Issue by seralo** [Makuna/NeoPixelBus#132]
NeoPixelBus::ClearTo(typename T_COLOR_FEATURE::ColorObject color, uint16_t first, uint16_t last)

If first == last to set only one pixel, the function does not work.
(As expected if last=first+1 it will set two pixels, but if we want to set only one pixel the function does nothing)

It would be nice to be able to change also only one pixel with the same function and not have to call SetPixelColor when we have only one pixel to change.

**Comment by Makuna** [comment]
new release published with fix
