### ISSUE TITLE
Description in Arduino Library lists "ADA102" instead of "APA102"

### ISSUE THREAD

**Issue by grndkntrl** [Makuna/NeoPixelBus#141]
Hi, just a FYI, it's wrong in both library.json & library.properties. So if searching for "APA102" in the Arduino library manager, your library won't show up in the results.

**Comment by Makuna** [comment]
thanks for catching that.  Fix will be coming soon with some other changes.

**Comment by Makuna** [comment]
should be fixed

**Comment by grndkntrl** [comment]
Yep, confirmed. It's just rolled over into the latest hourly update into the library manager. Thanks!
