### ISSUE TITLE
Fade pixel out of bounds causes intermittent crash

### ISSUE THREAD

**Issue by sticilface** [Makuna/NeoPixelBus#15]
if you use setpixelcolor and incorrectly assign a pixel above how many you have... it is fine.. (or seems to be) if you use LinearFadePixelColor and accidentally do that... it becomes very unstable, crashing intermittently....

i'm assuming you get a buffer overrun... and it crashes... but crucially.. only sometimes.. (i guess it depends on adjacent memory..

**Comment by Makuna** [comment]
This has been fixed.
