### ISSUE TITLE
Support for circular displays?

### ISSUE THREAD

**Issue by jteiwes** [Makuna/NeoPixelBus#150]
The Matrix Panel Support can be used to structure a rectangular or even quadratic display of ws2812 LEDs. 

Currently i am trying to apply this to a circular display. I made a sketch of the layout here:

![zeichnung](https://cloud.githubusercontent.com/assets/3096788/21719001/88ba4496-d41b-11e6-8a51-df6d5f83e955.png)

As far as i understand it this display cannot be structured using the matrix panel support since every line has a different number of columns. 

Can anybody give a hint on where to integrate this into the library or how to achieve this?

**Comment by Makuna** [comment]
A beginning of documenting this as a Wiki topic.
https://github.com/Makuna/NeoPixelBus/wiki/Spiral-Topography

**Comment by Makuna** [comment]
#154

**Comment by jteiwes** [comment]
Thanks a lot, i will have a try at this one.. Looks really good!
