### ISSUE TITLE
Please note direct info about esp8266 pin

### ISSUE THREAD

**Issue by truebucha** [Makuna/NeoPixelBus#165]
I searched info about the default pin looking through all wiki and found no mention. Only comment in test ino helped me well.
please add this
// For Esp8266, the Pin is omitted and it uses GPIO3 due to DMA hardware use.  
here 
[wiki](https://github.com/Makuna/NeoPixelBus/wiki/NeoPixelBus-object)

**Comment by penfold42** [comment]
I agree it's not obvious but it is there:

https://github.com/Makuna/NeoPixelBus/wiki/NeoPixelBus-object#neoesp8266dma800kbpsmethod

**Comment by Makuna** [comment]
@truebucha, in the link you listed, its states it also.

"For the Esp8266 platforms, just omit the pin argument. This is due to hardware support that doesn't allow for selecting a pin."
