### ISSUE TITLE
Channels, what are they?

### ISSUE THREAD

**Issue by exothink** [Makuna/NeoPixelBus#190]
What are animation channels?

Please provide an example on how to use multiple channels.

Thanks,
John

**Comment by Makuna** [comment]
Did you get a chance to review the animation examples that are part of the library? 
Almost all of them use multiple channels.

Did you get a chance to review the wiki?
See [Wiki entry for NeoPixelAnimator object](https://github.com/Makuna/NeoPixelBus/wiki/NeoPixelAnimator-object)
