### ISSUE TITLE
Compilation error on example sketch NeoPixelAnimation

### ISSUE THREAD

**Issue by pacobyte** [Makuna/NeoPixelBus#193]
Arduino IDE version: v1.8.5
Board: Arduino UNO
LED Chipset: SK6812 RGBW, 60 count

The next example sketch to give me a compilation error after my previously-reported NeoPixelCylon is NeoPixelAnimation. Here's the error:
```
NeoPixelAnimation:145: error: conversion from 'Neo4Elements::ColorObject {aka RgbwColor}' to non-scalar type 'RgbColor' requested
```

**Comment by Makuna** [comment]
Its the same issue as the other.

Your strip is defined to use a RgbwColor but you are assigning a pixel color to a RgbColor variable.  You need to modify the sketch to use RgbwColor.

**Comment by pacobyte** [comment]
Thank you again. Problem solved.
