### ISSUE TITLE
Add function to swap pixel colors

### ISSUE THREAD

**Issue by markg85** [Makuna/NeoPixelBus#194]
Hi,

I found it rather useful to have a function to swap the pixel color with another pixel.
My implementation (in NeoPixelBus.h, feel free to use this code as you wish):
```cpp
    void SwapPixelColor(uint16_t one, uint16_t two)
    {
      auto colorOne = GetPixelColor(one);
      auto colorTwo = GetPixelColor(two);
      T_COLOR_FEATURE::applyPixelColor(_method.getPixels(), one, colorTwo);
      T_COLOR_FEATURE::applyPixelColor(_method.getPixels(), two, colorOne);
      Dirty();
    };
```
You can implement some things with this as base. Like a rotating dot (even though you have the "Rotate" method for that) or just if you want to swap pixels without wanting to get their colors first. It's just a cleaner way in that scenario.

I'm not sure if this is beneficial to have for others. It's probably dependent on the usecase. I had a use for it thus made it :)

Best regards,
Mark Gaiser

**Comment by Makuna** [comment]
https://github.com/Makuna/NeoPixelBus/pull/221
