### ISSUE TITLE
Conversion from HSL to HTML

### ISSUE THREAD

**Issue by BigAl66** [Makuna/NeoPixelBus#203]
Is there a direct way to convert a HSL color to a HTML color? I try at the moment the following workaround:

  HslColor hsl(0.5f, 1.0f, 0.5f);
  RgbColor rgb = hsl;
  HtmlColor html = rgb;

If I read the faq there is written: 

> There is a HslColor object that will automatically convert to any of the other color object by just assigning them. The color objects are RgbColor, RgbwColor, HslColor, HsbColor, and HtmlColor.

A direct asignment "html = rgb" results in an compiler error:

> error: conversion from 'HslColor' to non-scalar type 'HtmlColor' requested

**Comment by Makuna** [comment]
Using Gitter is the better approach at asking questions. [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Makuna/NeoPixelBus?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

Currently only RgbColor will auto convert to any other.  This was done to minimize the accidental expensive conversions.  You can do what you want by doing this...
```
HslColor hsl(0.5f, 1.0f, 0.5f);
HtmlColor html = RgbColor(hsl);
```

**Comment by BigAl66** [comment]
Hi Makuna,
thank you for your answer. Yes I will use this way - and yes I will have a look to Gitter. I'm so happy to found this well documented library because since weeks I try to get my project stable and now it is :-).
