### ISSUE TITLE
Question: Scrolling Text

### ISSUE THREAD

**Issue by gerrus** [Makuna/NeoPixelBus#234]
Hi,
how can I somehow make scrolling text with the library?on a matrix of several rows ws2812b
thx

**Comment by Makuna** [comment]
When you created this, did you read the top (copied below).

**NOTE:  If you are seeking help or have questions, this is NOT the place to do it.**  For questions and support, jump on Gitter and ask away.  
[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Makuna/NeoPixelBus?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
