### ISSUE TITLE
Compilation error for examples on ESP8266 (Wemos D1 mini)

### ISSUE THREAD

**Issue by FrankenApps** [Makuna/NeoPixelBus#261]
Arduino 1.8.5 on Windows 10
Wemos D1 mini
Whenever I try to compile any of the example sketches, I get the following compiler error:
I attached the full Traceback
[log.txt](https://github.com/Makuna/NeoPixelBus/files/3048422/log.txt)
I'm sorry it is in german.

**Comment by Makuna** [comment]
Please include ALL versions of pieces.  You didn't mention which board support version (see board manager) and which version of the NeoPixelBus library (see Library Manager).

Also, update your Arduino IDE, they often induce small bugs that effect compilation then quickly fix it with a version update.  I am running 1.8.9 and don't see this problem.

**Comment by FrankenApps** [comment]
Well, I resolved my issue. It was not a problem with the library.
I had another esp8266 SPI library installed on my system, that was used instead of the one installed by the board manager.
The Arduino IDE actually told me in the third last line of the error log, I just did not see it.
Sorry for the inconvenience.
