### ISSUE TITLE
example ESP32 mulistrip

### ISSUE THREAD

**Issue by laserdave** [Makuna/NeoPixelBus#279]
Hi there nice compact library I love it. Do you have any multistrip examples with animations RMT or i2s

**Comment by Makuna** [comment]
General questions should not be asked in the Issues.  Use Gitter as mentioned in the readme and the wiki.
I modified your question into a feature request.

NOTE:  I do not provide platform specific examples, this library is targeted to be cross platform.

**Comment by Makuna** [comment]
And now I am closing this as I already have one tracking something similiar.
https://github.com/Makuna/NeoPixelBus/issues/160
