### ISSUE TITLE
Bitbang timing change / option request. T0H 

### ISSUE THREAD

**Issue by RudyFiero** [Makuna/NeoPixelBus#285]
**Describe the bug**
I tried to use the bitbang option and always got full brightness->white. I used the Adafruit library with the same hardware without issue. I used a logic analyser to see if there was any timing differences, and see how they compared to a SK6812 data sheet. With the NeoPixelBus output the width of T0H was wider than the tolerance given in the spec sheet. 
http://www.szledcolor.com/download/SK6812%20LED.pdf

I then found the file that generated the bit output with the following defines. 

NeoPixelBus/src/internal/NeoPixelEsp.c

**#define CYCLES_800_T0H (F_CPU / 2500000) // 0.4us**
#define CYCLES_800_T1H (F_CPU / 1250000) // 0.8us
#define CYCLES_800 (F_CPU / 800000) // 1.25us per bit

changed to,
#define CYCLES_800_T0H (F_CPU / **2900000**) // 

Measured timing was now 0.375uS - 0.4167uS. And this fixed the output problem. The code now drove the LEDs properly.

The current library value 
**#define CYCLES_800_T0H (F_CPU / 2500000) // 0.4us**
produced T0H values from 0.46uS - -.50uS. I had none that produced the 0.4uS listed.

I had used a compiled version of Sonoff-Tasmota software for the ESP8266. 
https://github.com/arendst/Sonoff-Tasmota
It listed a control option for the WS2812 so I tried it. I got only full white output. Looking through that repository I found the NeoPixelBus code and came here. I downloaded this library and compiled the NeoPixelTest.ino example. It produced exactly the same response as the Tasmota code, as expected. That was when I pulled out the logic probe and did the timing investigation.

The count value of 2900000 was an arbitrary pick. A starting point, and it worked. Today I did the timing measurement and based on what I measure, I have no reason to try different values other than the 2900000 I picked. I'm sure there could be some minor tweaking but my guess is that it will make little difference to the performance.

The 2900000 does change the period from 1.25uS to 1.2917uS most of the time, with some being 1.25uS. 

I had opened an issue on the Sonoff-Tasmota repository before I found that they were using the NeoPixelBus library. I posted more information there but only posted the relevant information here. 
https://github.com/arendst/Sonoff-Tasmota/issues/6292

I did my measurements on a ESP-07S module. Measurements were taken with a Saleae 24MHz logic probe.

**Comment by RudyFiero** [comment]
I changed the code as per your instructions, but there was no difference in T0H. Typically 0.4583uS or 0.50uS.

What I did see was that the period of a bit changed from 1.25uS to 1.2915uS, the same as the change that I had made modifying only the count/divisor. Not significant as far as I'm concerned, but it doesn't have any effect on what needs to change.

**Comment by Makuna** [comment]
That problably came from me also (here is my [code](https://github.com/Makuna/NeoPixelBus/blob/c71e200dd6ba9634e9f3655b8569f2794051a6f3/src/internal/NeoEspBitBangMethod.h#L38)) but it should not be an issue anymore as I believe that got fixed last year.

Try these changes
https://github.com/Makuna/NeoPixelBus/pull/286

With these, if you run at 160mhz it is fully fixed, at 80mhz, you will still see 500ns high pulses at times.  BUT, I ran the Adafruit code and I see the same thing (most are near 450ns, but some are 500ns).  This maybe right on the edge and the improvements I provided to match the optimizations Adafruit has done might bring it within a working range.

**Comment by RudyFiero** [comment]
It didn't work for me at 80MHz, but it is working at 160MHz. 

Looking at your code I see an option for the SK6812. 
NeoEspBitBangSpeedSk6812

I am using your NeoPixelTest.ino sketch. What do I need to change to use the code for the SK6812?
This is what I am using, that works at 160MHz,
NeoPixelBus<NeoGrbFeature, NeoEsp8266BitBang800KbpsMethod> strip(PixelCount, PixelPin);

I am a hardware designer, not a programmer. I can do some programming, but I don't have a strong foundation.

**Comment by RudyFiero** [comment]
The timing I get at 160MHz (without specifying the SK6812) is  0.467uS - 0.4583uS
No 0.50uS as I had before with the older code. That is working but I think it is **just** working.

**Comment by Makuna** [comment]
Use NeoEsp8266BitBangSk6812Method; but currently bit bang doesn't use different timing yet so its really only different in the reset time.
```
NeoPixelBus<NeoGrbFeature, NeoEsp8266BitBangSk6812Method> strip(PixelCount, PixelPin);
```
What timing  are you seeing with Adafruit?  I see the same between my code and theirs now.  The code difference now is pretty small (I have one less assignment during the high pulse, so it should be more accurate than theirs, but I think instruction cycles are getting in the way).

**Comment by RudyFiero** [comment]
Yes it looks the same as the Adafruit timing.  I think that is a little out of spec for the SK6812 but it should work.

**Comment by RudyFiero** [comment]
This is good enough for me. This was more a test to try out the Tasmota software. I'm ok with closing the issue.

**Comment by Makuna** [comment]
https://github.com/Makuna/NeoPixelBus/pull/287
I believe this is what you were doing originally but it wasn't clear as to why you were doing it.  
This brings the timing way closer.

**Comment by RudyFiero** [comment]
I thought there was some overhead that wasn't being taken care of. My quick fix was to shorten the expected time. Not a great solution but considering what I know about the details of the underlying  code/hardware it was the best I could do.
