### ISSUE TITLE
WS2811 not working with ESP32

### ISSUE THREAD

**Issue by uuperi** [Makuna/NeoPixelBus#295]
Hi.

I tried to control my WS2811 RGB-led strip using an ESP32 but it didn't respond at all.
Then I tried replacing the controller with Arduino Mega - worked flawlessly. Then I tried ESP32 with WS2815 - no problem at all.

**Comment by Makuna** [comment]
General support should be directed to the Gitter channe,  as mentioned in the readme and wiki.  Here is a link to it.
[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Makuna/NeoPixelBus?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
If you go there I can help you out.

The "issues" area of GitHub is not a support forum.  Further, "issues" should follow one of the supplied templates, of which this does not.
