### ISSUE TITLE
Parallel output for multiple platforms

### ISSUE THREAD

**Issue by Yordi-B** [Makuna/NeoPixelBus#311]
#Hi Guys,
Great job on the library, with all the added support.

Im currently using it for the RGBW color modes provided.

Since my LED project is getting bigger 2700 Leds. Im trying to find a solution to operate multiple parallel channels.

Ive noticed this is available for the ESP methods.

For the Teensy 3.2 im using FastLed provides a parallel output in combination with the octows2811 adapter. But no rgbw support.

Would it be possible to achieve this with neopixel, basicly suggesting an added feature for parallel output on teensy 3.X.

**Comment by Makuna** [comment]
https://www.pjrc.com/teensy/td_libs_OctoWS2811.html

**Comment by Yordi-B** [comment]
I'm unsure what you mean with the link.
Are you suggesting i use the OctoWS2811 library instead?

Good suggestion, unfortunately it doesnt support RGBWW I'm so desperately in need off.

**Comment by Makuna** [comment]
Its just a reference link, nothing more.

**Comment by Makuna** [comment]
already trackd by https://github.com/Makuna/NeoPixelBus/issues/160
