### ISSUE TITLE
CubicCenter Wrong

### ISSUE THREAD

**Issue by mriksman** [Makuna/NeoPixelBus#336]
NeoEase::CubicCenter function is wrong. Input 1.0f, and it outputs 1.5f.

This;
`return (0.5f * (unitValue * unitValue * unitValue) + 1);`
Should be;
`return (0.5f * (unitValue * unitValue * unitValue + 1));`

**Comment by Makuna** [comment]
you can make a pull request with the change.

**Comment by Makuna** [comment]
https://github.com/Makuna/NeoPixelBus/pull/337

**Comment by Makuna** [comment]
v2.5.7 just made; might take a day to make it through the Arduino update process.
