### ISSUE TITLE
Is it possible, to program the ESP 2866 direktly with this libary (from linux as operaring system),without the adruino IDE?

### ISSUE THREAD

**Issue by CarlosMenke** [Makuna/NeoPixelBus#350]
**NOTE:  If you are seeking help or have questions, this is NOT the place to do it.**  For questions and support, jump on Gitter and ask away.  
[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Makuna/NeoPixelBus?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Makuna** [comment]
Did you read the first line of your issue?  This is not the place to ask questions.  Jump on gitter to do that.
