### ISSUE TITLE
8-bit calculation, instead of 16-bit leads to data loss

### ISSUE THREAD

**Issue by BlueAndi** [Makuna/NeoPixelBus#359]
https://github.com/Makuna/NeoPixelBus/blob/ad38b97f8b839427a72bf681c10eb3da5610ec03/src/internal/RgbColor.h#L179-L182

This leads to a 8-bit multiplication/addition/division, instead of 16-bit.

Similar problem here:
https://github.com/Makuna/NeoPixelBus/blob/ad38b97f8b839427a72bf681c10eb3da5610ec03/src/internal/RgbColor.h#L186

**Comment by Makuna** [comment]
https://github.com/Makuna/NeoPixelBus/pull/360

**Comment by BlueAndi** [comment]
Looks good, thanks.
