### ISSUE TITLE
esp32 i2s - i2sSignal may be unitialized

### ISSUE THREAD

**Issue by BlueAndi** [Makuna/NeoPixelBus#365]
https://github.com/Makuna/NeoPixelBus/blob/23751b1c6d64b7a6fa54ad39edf555cf61526657/src/internal/Esp32_i2s.c#L253-L264

![grafik](https://user-images.githubusercontent.com/9699465/91566358-d4c54480-e943-11ea-8622-d448e6b84e73.png)

The "else" looks wrong in case its not a esp32s2, because the gpio_matrix_out() will be in the "else" part.

**Comment by Makuna** [comment]
Good catch.
The #else should just be an #end and the other #end should be removed.  There is another spot I found with the exact same issue.

**Comment by Makuna** [comment]
https://github.com/Makuna/NeoPixelBus/pull/366

**Comment by Makuna** [comment]
https://github.com/Makuna/NeoPixelBus/releases/tag/2.6.0
