### ISSUE TITLE
reconfig method request

### ISSUE THREAD

**Issue by yuranikspb** [Makuna/NeoPixelBus#373]
Make a reconfiguration method that allows, to change settings  dynamically.
for example:
esp32 config via bluetooth
depending on what type of LEDs and their number are connected to the pin

**Comment by Makuna** [comment]
You didn't follow the issue template and your description is rather terse.

I suspect you mean, unravel the use of templates or provide an abstract base class; both of which are counter to the primary goal of producing the smallest code memory footprint.

A complete rewrite or even a major design change is not on the plans.  The above request is of little priority to most "makers" as their projects are static in nature.
