### ISSUE TITLE
strip.Show() stops ESP

### ISSUE THREAD

**Issue by linus1999** [Makuna/NeoPixelBus#386]
Hello,

I am using this [https://github.com/256dpi/arduino-mqtt] Library for MQTT handling.
If I call strip.Show() using the DMA Method on an ESP8266, the ESP just stops.
It isn't resetting, but also doesn't continue. Your Example without the MQTT library just works fine.

Any idea, what could cause this problem?

Best regards

**Comment by Makuna** [comment]
This is a question, best asked on the Gitter channel or the new Github Discussions feature.
