### ISSUE TITLE
Strip.show() sometimes not outputting stuff to LEDs (WS2812)

### ISSUE THREAD

**Issue by nouser2013** [Makuna/NeoPixelBus#419]
**Describe the bug**
In short, `strip.Show()` sometimes does not output strip data to the LEDs. I've connected 6 LEDs to an ESP32 and I initialize the strip like so and I use it (hopefully) correctly:
```c++
NeoPixelBrightnessBus<NeoGrbFeature, NeoEsp32I2s1800KbpsMethod> strip(6, 23);
void setup() {
  strip.Begin();
  strip.Show();
}
void loop() {
  // ...
  // many of those across the whole project. All failing seemingly randomly...
  strip.SetPixelColor(0, RgbColor(0, 255, 0));
  strip.Show();
}
```
I'm using the latest version `2.6.1`.

**To Reproduce**
Unfortunately, this is sporadic behavior. I cannot clearly reproduce it. Also, I was not able to determine which version the bug was introduced. Also, I don't know whether this is a Arduino Core problem or if it's with this library, I usually keep everything updated to the latest version, also the core from GIT.

**Expected behavior**
Obviously, I'd expect the strip to show the respective colors after calling `strip.Show()`.

**Comment by Makuna** [comment]
You created a duplicate to https://github.com/Makuna/NeoPixelBus/issues/292  

Known bug.  Don't use I2s right now.  There is a problem in the core.
