### ISSUE TITLE
Support for lower SPI frequencies

### ISSUE THREAD

**Issue by altery** [Makuna/NeoPixelBus#422]
An old project I'm migrating to NeoPixelBus+ESP8266 uses a rather long SPI wire and does not work reliably with high bandwidth transfers rates. Would it be possible to extend the supported SPI frequencies with lower rates (such es 1MHz and 0.5MHz)?

**Comment by Makuna** [comment]
I will add those.

You can provide your own speeds by using the following example for testing In the mean time...
```
class MySpiSpeed {
public:
    static const uint32_t Clock = 1000000L; // 1mhz;  2000000L = 2mhz
};

typedef Lpd6803MethodBase<TwoWireSpiImple<MySpiSpeed>> Lpd6803SpiMySpeedMethod;
```
Then you can use Lpd6803SpiMySpeedMethod for your custom speed.

**Comment by Makuna** [comment]
https://github.com/Makuna/NeoPixelBus/pull/423

**Comment by altery** [comment]
Thanks for the quick implementation! I hope it's ok, if I resolve the issue myself?

**Comment by Makuna** [comment]
Not sure you have seen it, but I also added a dynamic SPI speed setting method.  Its talked about in the discussion but not yet exposed in the Wiki.

See https://github.com/Makuna/NeoPixelBus/discussions/433

**Comment by altery** [comment]
No, had not seen it, thanks for pointing that out!
