### ISSUE TITLE
Allow raw initialization of Rgb16Color

### ISSUE THREAD

**Issue by altery** [Makuna/NeoPixelBus#444]
I'm using NeoPixelBus as 'backend' for the [adafruit GFX library](https://github.com/adafruit/Adafruit-GFX-Library). The library supplies color information in RGB 5/6/5 Format as uint16_t, so it would be ideal if the Rgb16Color could be directly initialized with this value (a constructor that directly assigns a uint16_t to _c).

**Comment by Makuna** [comment]
https://github.com/Makuna/NeoPixelBus/pull/454

**Comment by Makuna** [comment]
v2.6.3
