### ISSUE TITLE
WS2814 support

### ISSUE THREAD

**Issue by tohox** [Makuna/NeoPixelBus#449]
*** EDIT ***

Please ignore my original request. Finally got it working with (NeoRgbwFeature, Neo800KbpsMethod). Turns out both the DIN and BIN pins of the first controller must be connected to the Arduino's data output pin for things to align properly. Sorry for the unneeded feature request!

*** END OF EDIT ***

Hi, 

Have been trying to get a feature/method combination to work with these RGBW drivers without success. Unfortunately very little documentation available. Each chip drives 1 RGBW pixel from a single DIN pin (there is also a BIN backup pin) at 800kbps (8 bits per color).

This is all I could find (Chinese only) : https://datasheet.lcsc.com/szlcsc/2012110135_Worldsemi-WS2814_C965562.pdf

Let me know if I can help.

Thanks!

**Comment by Makuna** [comment]
Correct, either the Neo800KbpsMethod or the NeoWs2812xMethod will work well.

Those double DIN chips catch many people off guard.  The first one has them connected to the output on the uC.  After that the DIN2 is connected to the one before the one before; its a mechanism that allows the strip to continue to work if a single LED goes into a fault mode.
