### ISSUE TITLE
Publish to Conan Center

### ISSUE THREAD

**Issue by mcandre** [Makuna/NeoPixelBus#475]
**NOTE:  If you are seeking help or have questions, this is NOT the place to do it.**  For questions and support, jump on Gitter and ask away.  
[![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/Makuna/NeoPixelBus?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)

**Is your feature request related to a problem? Please describe.**

Publishing this library to ConanCenter will simplify the installation process for many users.

**Describe the solution you'd like**

Publish NeoPixelBus to Conan Center.

https://conan.io/center/

**Comment by Makuna** [comment]
This is an Arduino library, the installation is already part of the Arduino Library Manager installation process.  Why would this make it any simplier?

**Comment by Makuna** [comment]
No response to question for over a year; closing.
