### ISSUE TITLE
breaking change | esp8266 sdk version >= 3.0.1 | I2S.h

### ISSUE THREAD

**Issue by coelner** [Makuna/NeoPixelBus#485]
With the esp8266 sdk version 3.0.1 onwards: https://github.com/esp8266/Arduino/pull/8108
will break this line: 

https://github.com/Makuna/NeoPixelBus/blob/2ff885c702a6d9f7a7ce6a80fd48512fa7c71085/src/internal/NeoEsp8266DmaMethod.h#L42

**Comment by Makuna** [comment]
https://github.com/Makuna/NeoPixelBus/pull/486

**Comment by akarnani** [comment]
Would it be possible to cut a release with the above pull request included?  It would be nice to be able to pull in these changes with the library manager.

**Comment by coelner** [comment]
The release 3.0.1 is officially available: https://github.com/esp8266/Arduino/releases/tag/3.0.1

I do not know any method to determine which version is installed and select through a precomiler flag the right code snippet.

**Comment by Makuna** [comment]
v2.6.5
