### ISSUE TITLE
Incorrect RMT typedef method specified for TM1914

### ISSUE THREAD

**Issue by blazoncek** [Makuna/NeoPixelBus#494]
https://github.com/Makuna/NeoPixelBus/blob/4438ba517c34ad6bb388226c158882e7d69d335c/src/internal/NeoEsp32RmtMethod.h#L665

Incorrect RMT method specified.
Does not compile for ESP32S2.

**Comment by Makuna** [comment]
https://github.com/Makuna/NeoPixelBus/pull/495

**Comment by Makuna** [comment]
https://github.com/Makuna/NeoPixelBus/releases/tag/2.6.6
