### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by sticilface** [Makuna/NeoPixelBus#5]
I was wondering if you could provide a bit more info on the way animations work.  I can't seem to satisfy my understanding just looking at the code..  It uses timers when the update animations is called to work out if it is time to update the string...  The code below works fine.... 

```````
void SetRGBcolour (RgbColor value) {
   int amounttodarken = 255 - CurrentBrightness;
   value.Darken(amounttodarken);
    for (uint8_t pixel = 0; pixel < pixelCount; pixel++) {
        strip.LinearFadePixelColor(1000, pixel, value);
    }
}
```````````
but if i increase the time, to 5000 (fade over 5 seconds, the ESP just reboots...)

**Comment by Makuna** [comment]
Darken doesn't take an int, it takes a uint8_t (0-255).  The compiler might auto convert but do you know what it does if the value is greater than 255 or less than zero?

How many pixels are you driving?

What does your update loop look like?  There are two "models" you can use.  Always updating/animating or periodic updating/animating.  The key difference between them is the use of the IsAnimating() and StartAnimating(), where these two are only used with the periodic model.  


the important part of both models is that you need too allow the animations to "run" by periodically calling .UpdateAnimations() and .Show().  For a minimum this should be happen at least 10 times a second, 30 times a second is better.

This is copied from a sample, showing how to continue all animations until they are all complete, calling the methods 30 times a second.  This sample is using the periodic model where it only updates when there are animations that your application tracks.
```
// start animating
  strip.StartAnimating(); 
 // wait until no more animations are running
  while (strip.IsAnimating())
  {
    strip.UpdateAnimations();
    strip.Show();
    delay(33); // ~30hz change cycle
  }
```
If after all animations have stopped, and then you start more, you need to call the .StartAnimating() before entering the above loop.

The other model, you just always call UpdateAnimations() and Show() at a fast rate, then there is no need to call .StartAnimating() nor check for IsAnimating(), 
```
void loop() {
    // other code that effects the application, but don't take up more than 500ms or the chip will reset

    strip.UpdateAnimations();
    strip.Show();
    delay(33); // ~30hz change cycle, optional,  this could be removed and will fine
  }
```
