### ISSUE TITLE
Create function HsbColor::Darken

### ISSUE THREAD

**Issue by orlov-bug44** [Makuna/NeoPixelBus#505]
Because RgbColor::Darken is blends origin color on low brightness.

**Comment by Makuna** [comment]
HSB or HSL, darken is just lower the B or L value.
```
HsbColor color(0.3,1.0,0.8);
color.B -= 0.1; // this will darken
color.B += 0.2; // this will lighten
```
of course, you need to maintain the value of B between 0.0 and 1.0 for consistency.

**Comment by orlov-bug44** [comment]
thnx. )
