### ISSUE TITLE
Add NeoPixelBuff constructor without parameters.

### ISSUE THREAD

**Issue by far5893** [Makuna/NeoPixelBus#54]
I try to change pixel number after read configuration from outside.
My code:
NeoPixelBus * strip;
main(){
.......
	NeoPixelBus b = NeoPixelBus(configuration.lednum, pixelPin);
	strip = &b;

.....
}
I receive a bad Exception(29) reset trying to use 
in a function
	                    strip->ClearTo(c);
	                    strip->Show();
	                    delay(1);
	                    strip->Pause();

**Comment by Makuna** [comment]
There is a specific reason to not have the parameter-less constructor.

If you want to dynamically change core feature (pin, count of pixels, and flags), you just need to create a new one.
Your code is incorrect, this...

```
NeoPixelBus b = NeoPixelBus(configuration.lednum, pixelPin);
 strip = &b;
```
 creates the NeoPixelBus on the stack (local to current call of the function) and then saving a pointer to it and using it outside the lifetime of that call (bad, very bad).

What you want to do is create one on the heap.
```
NeoPixelBus* pStrip = NULL;  // using the little p to make it obvious this is a pointer to the object, not an instance; and initialize to null

main() {
...
  if (pStrip) delete pStrip; // get rid of the old one if there was one
  pStrip = new NeoPixelBus(configuration.lednum, pixelPin); // allocate a new one on heap 
...
pStrip->ClearTo(c);

}
```
