### ISSUE TITLE
Error when using DotStarEsp32DmaSpiMethod

### ISSUE THREAD

**Issue by mr-tm** [Makuna/NeoPixelBus#540]
**Describe the bug**
I have 2 strips initialized dynamically by
```
Leds = new NeoPixelBrightnessBus<DotStarBgrFeature, DotStarEsp32DmaVspiMethod> (144, 18, 23);
Leds2 = new NeoPixelBrightnessBus<DotStarBgrFeature, DotStarEsp32DmaHspiMethod> (144, 14, 13);

Leds->Begin();
Leds2->Begin();
```

Error seems to happen when trying to show lights on strip.
```
assertion "ret == ESP_OK" failed: file ".pio\libdeps\esp32dev\NeoPixelBus\src/internal/DotStarEsp32DmaSpiMethod.h", line 214, function: void DotStarEsp32DmaSpiMethod<T_SPISPEED, T_SPIBUS>::Update(bool) [with T_SPISPEED = SpiSpeed10Mhz; T_SPIBUS = Esp32VspiBus]
abort() was called at PC 0x400f5b23 on core 1
```

Libraries I'm using in the project:
ArduinoJson 6.18.5
NeoPixelBus 2.6.9
SPI 1.0
BluetoothSerial 1.0
EEPROM 1.0.3
WiFi 1.0
HTTPClient 1.2
WiFiClientSecure 1.0
Update 1.0

NeoPixelBrightnessBus<DotStarBgrFeature, DotStarVspiMethod>
NeoPixelBrightnessBus<DotStarBgrFeature, DotStarHspiMethod>
combination seems to be working fine.

**Development environment:**
 - OS: Win11
 - Build Environment PlatformIO
 - Board target Espressif 32 (3.4.0+sha.495c689) > Espressif ESP32 Dev Module
 - Library version v2.6.9

Anyways, great library! Been using it extensively on Sk6812 RGBW LEDS without any problems.

**Comment by Makuna** [comment]
Please provide a minimal sketch that duplicates the error.
