### ISSUE TITLE
Please provide a library.json for platformio

### ISSUE THREAD

**Issue by probonopd** [Makuna/NeoPixelBus#62]
It would be nice if a `library.json` for [platformio](http://platformio.org/) could be included.

**Comment by Makuna** [comment]
V2beta branch has one present but it is not yet registered. This branch will become the source in the near future.

**Comment by probonopd** [comment]
Thanks @Makuna

**Comment by Makuna** [comment]
you may register it for me if you like.  I am not a platformio user and every time I try to install it, some component step fails due to conflicts with other stuff I have on my computer.  So I have never taken the final step of registering it.
