### ISSUE TITLE
RgbColor object

### ISSUE THREAD

**Issue by sticilface** [Makuna/NeoPixelBus#7]
Is there a way to work with the individual colours in an rub object? 

you can set it ```test = RgbColor(r,g,b)``` but can you go back from it to get the r,g,b components from test?

You lib is working very well by the way, the new level interrupts make is smooth as butter.  I've driven 260 LEDs, without a flicker...

**Comment by Makuna** [comment]
The individual color components are exposed.
```
test.R = 12;
test.G = 255;
if (test.B == 129){
  test.B = 0;
}
else {
  test.B++;
}
```

**Comment by sticilface** [comment]
Thank you again!
