### ISSUE TITLE
Teensy - missing uint8_t in latest

### ISSUE THREAD

**Issue by dimitre** [Makuna/NeoPixelBus#826]
I'm having this issue when using latest from github
installing latest release in platformio it compiles OK
Thank you for the great lib!

```
.pio/libdeps/development/NeoPixelBus/src/internal/methods/FractionClk.c:40:32: error: unknown type name 'uint8_t'
   40 | void UnitDecimalToFractionClks(uint8_t* resultN,
      |                                ^~~~~~~
.pio/libdeps/development/NeoPixelBus/src/internal/methods/FractionClk.c:30:1: note: 'uint8_t' is defined in header '<stdint.h>'; did you forget to '#include <stdint.h>'?

```

**Comment by Makuna** [comment]
thanks, it looks like on that platform stdio.h doesn't include stdint.h.  I will get a fix soon.

**Comment by Makuna** [comment]
https://github.com/Makuna/NeoPixelBus/pull/827

**Comment by Makuna** [comment]
https://github.com/Makuna/NeoPixelBus/releases/tag/2.8.1
