### ISSUE TITLE
Teensy 4.1 support

### ISSUE THREAD

**Issue by dimitre** [Makuna/NeoPixelBus#847]
It seems Teeny 4.1 is not supported now, it would be great if this lib could support it
I've noticed Adafruit_NeoPixel seems to support it so the data timing variables can be seen here:
https://github.com/adafruit/Adafruit_NeoPixel/blob/aa798ff5e9bb9d7299190627d2454ccd6f599ae8/Adafruit_NeoPixel.cpp#L1900

Edit: I have the hardware to test here and validate

Thank you

**Comment by dimitre** [comment]
closed by https://github.com/Makuna/NeoPixelBus/pull/849

**Comment by Makuna** [comment]
Issues remain open until they get released.
Just add the pending attribute.

**Comment by Makuna** [comment]
https://github.com/Makuna/NeoPixelBus/releases/tag/2.8.3
