### ISSUE TITLE
Add support for these possibly proprietary WS2805 lights

### ISSUE THREAD

**Issue by Slyke** [Makuna/NeoPixelBus#865]
**Is your feature request related to a problem? Please describe.**
Purchased some garden flex lights and almost have them working correctly with WLED. They just never show the color blue.

**Describe the solution you'd like**
Support for these WS2805 lights.

**Describe alternatives you've considered**
Compiling NeoPixels and WLED with modified timings.

**Additional context**

Diagnosing the issues with my oscilloscope, it appears that there's a quiet zone of 2 bits after each byte of the between each of the 4 bytes for each pixel. The quiet zone also exists in WLED, but is significantly shorter. The symptom is that the lights never show the color blue, as the byte phases are misaligned at some point during the green byte, and instead blue appears to be some variant of white.

These are the lights in question:
![image](https://github.com/user-attachments/assets/34e9598b-158f-435c-b29f-ac0d869491a8)

Here are some screenshots taken from my oscilloscope from the proprietary controller. Note the step differences between 5 and 20us:
Blue:
![blue_ctrl_1](https://github.com/user-attachments/assets/44bec78d-5c45-4e33-8d3a-64b8cbd3e28d)
![blue_ctrl_2](https://github.com/user-attachments/assets/83c9a9ea-9142-487e-b2d6-1825231f4506)

Green:
![green_ctrl_2](https://github.com/user-attachments/assets/9401a947-099f-477f-9660-13e91a927506)
![green_ctrl_1](https://github.com/user-attachments/assets/457d7e8f-3906-485f-9e9e-b321a4a60e23)

Red:
![red_ctrl_2](https://github.com/user-attachments/assets/81adb928-20e1-493c-9e7f-6cf047e87a55)
![red_ctrl_1](https://github.com/user-attachments/assets/3948d43c-2f25-4941-ab11-878994fa41a1)

White:
![white_ctrl_2](https://github.com/user-attachments/assets/20075441-24cf-4704-aea2-ffb2a6dd8b64)
![white_ctrl_1](https://github.com/user-attachments/assets/3536f72c-3fa6-4695-b426-90195026972d)

WLED (Uses NeoPixels):
Blue:
![blue_wled](https://github.com/user-attachments/assets/3fd822dd-a905-46ad-bba2-9826ca75bc7f)

Green:
![green_wled](https://github.com/user-attachments/assets/8e753518-2a7e-4fee-8b74-c2d4b76e772f)

Red:
![red_wled](https://github.com/user-attachments/assets/38d8d715-dbbc-4c2b-a09c-677488c37192)

White:
![white_wled](https://github.com/user-attachments/assets/2ae16151-88e1-4fc9-b0f3-ce3f91b3357c)

WLED Settings:
![image](https://github.com/user-attachments/assets/40f05909-40b8-4e48-a660-8e42a2f73ff1)

**Comment by Makuna** [comment]
The WS2805 chip is a little particular about its speed; it is directly supported by my library, but I am unsure how WLED exposes and if they do yet as it was just added earlier this year. It does not require and spacing between bits/bytes/words/pixels.

From your captures it looks like the pause is between 16 bits (2 bytes) not 4 bytes.

Capture and display the actual pulse width of a single pulse for both a 0 (short positive pulse) and a 1 (long positive pulse).  Also capture the start and end of a pulse train, they are separated by a long silent (reset) time of at least 100us in size. 

Also, capture what your WLED output is, zoom in so the pulse form can be reviewed.

Often the inter-byte or inter-pixel delays that are seen are not a LED requirement, but a side effect of the controller and how they implement the output.  In your case, its inter-word (16 bits).  It is not easy to support this with the hardware peripheral use required by ESP chips to keep a consistent output.  The bit-bang method supports adding a inter-pixel delay; a previous investigation into these sorts of spacings.  But it was found out the true issue was improper signal level shifting and that these spacings are an artifact of the controller and a requirement of the LEDs. The ESP is 3.3v and the LEDs really needed a minimum of 3.7v (optimum 5v or even greater); getting this right with voltage level and pulse form (some round off the edges of the pulse and add noise/spikes at the leading edge).

**Comment by Slyke** [comment]
Ohh, I misread the reading, I thought the eight 0 bits afterwards were just clocking bits to help with synchronisation or something.
The WLED controller I use is an Anthom device I got from Aliexpress. Apparently they have good level shifters.

These readings were done with a 10x probe at 500mV steps on the stock controller from the manufacturer.

It appears a 1 is high for 1.25us with a low of 0.5us; and a 0 is high for 0.5us, and low for 0.5us.

1:
![SDS00021](https://github.com/user-attachments/assets/0e46eee9-cf32-4dd2-ae91-97445fca4641)

0 (with quiet zone after):
![SDS00027](https://github.com/user-attachments/assets/6f56e829-18cf-49a6-bfd5-438cdc13c364)

The quiet zone is 2.5us.

I also noticed that the stock controller was only sending out a signal once every second or so when set to a solid color. The lights might just latch their last received data.

Let me know if these help or you need any more readings from the controller. I have it until this weekend (I bought a second flex light just to test with and will return it once done).

**Comment by Slyke** [comment]
Oh and here are some more that might help diagnosis:
These are from the stock controller when it was set to green (it's RGBW). The first bit before the quiet zone is from red being 0:
![SDS00031](https://github.com/user-attachments/assets/aee2c055-d771-40d1-a7cd-54b282dc5cb2)

Here's the same reading, but offset so the first green bit is aligned with the grid:
![SDS00032](https://github.com/user-attachments/assets/4657e9fa-5473-42a5-a4e0-bd3d329beeee)

Here are some pics taken from the WLED controller, when it was set to red:
![SDS00033](https://github.com/user-attachments/assets/4d006aa6-559f-4de7-b172-6b11111e4483)

You can see that the bit times are a bit over half of what the stock controller outputs, with 1 being about 0.9us and 0 being 0.25us, and there is also no quiet zone after each section.

**Comment by Makuna** [comment]
It sounds like this is just a timing issue.

A WS2812x normal pulse (high plus following low) is 1.25us.  
Your LEDs look like they take 1.75us.  

If you select the **APA106** in WLED, that should get the timing closer, and it just may work with only that change.

**Comment by Slyke** [comment]
Using `APA106` caused the lights to become like a rainbow, so that didn't work.

I switched to `SM16825 RGBCW` and set the colors to GRB and the lights seem to work fine, even though the colors are apparently in the wrong order, they display correctly as set in the UI. This was another new light type added in the latest RC of WLED.

![image](https://github.com/user-attachments/assets/8f76b96a-14d8-46e0-b6d7-9ac0d49b032a)

Thanks for your help!

**Comment by Makuna** [comment]
In NeoPixelBus nomenclature, the color could be RGBWX. R, G, B, W, and followed by unused channel X.  This isn't uncommon.  Having these unused channels is defined by the X in the feature, often it is used to pad out to six channels, like RGBWWX or even RGBWXX.
